[project]
name = "MCP_Project1"
version = "0.1.0"
description = "First MCP Project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-groq>=0.3.7",
    "langchain-mcp-adapters>=0.1.9",
    "langgraph>=0.6.5",
    "mcp>=1.13.0",
]
